server:
  port: 8080

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/sulleong
#    username: sulleong
#    password: 1234
    url: jdbc:postgresql://3.39.254.24:5432/sulleong
    username: sulleong
    password: Sulleong104**
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate.default_batch_fetch_size: 1000
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: localhost
    port: 6379

image-base-url: https://sulleong.site/api/image/beer
#image-base-url: http://localhost:8080/image/beer