server:
  port: 8080

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://13.124.133.50:5432/sulleong
    username: sulleong
    password: Sulleong104**
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: localhost
    port: 6379

image-base-url: https://sulleong.site/api/image/beer
