server:
  port: 8080

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sulleong
    username: sulleong
    password: 1234
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate.default_batch_fetch_size: 1000
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: localhost
    port: 6379

  google:
    redirect-uri: ${GOOGLE_REDIRECT_URI}

domain: https://dev.sulleong.site
